"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SpriteTag = void 0;
var SpriteTag;
(function (SpriteTag) {
    SpriteTag[SpriteTag["solid"] = 0] = "solid";
    SpriteTag[SpriteTag["place"] = 1] = "place";
    SpriteTag[SpriteTag["ui"] = 2] = "ui";
    SpriteTag[SpriteTag["connection"] = 3] = "connection";
    SpriteTag[SpriteTag["tileable"] = 4] = "tileable";
    SpriteTag[SpriteTag["tileable_left"] = 5] = "tileable_left";
    SpriteTag[SpriteTag["tileable_right"] = 6] = "tileable_right";
    SpriteTag[SpriteTag["tileable_up"] = 7] = "tileable_up";
    SpriteTag[SpriteTag["tileable_down"] = 8] = "tileable_down";
    SpriteTag[SpriteTag["noConnection"] = 9] = "noConnection";
    SpriteTag[SpriteTag["L"] = 10] = "L";
    SpriteTag[SpriteTag["R"] = 11] = "R";
    SpriteTag[SpriteTag["LR"] = 12] = "LR";
    SpriteTag[SpriteTag["U"] = 13] = "U";
    SpriteTag[SpriteTag["LU"] = 14] = "LU";
    SpriteTag[SpriteTag["RU"] = 15] = "RU";
    SpriteTag[SpriteTag["LRU"] = 16] = "LRU";
    SpriteTag[SpriteTag["D"] = 17] = "D";
    SpriteTag[SpriteTag["LD"] = 18] = "LD";
    SpriteTag[SpriteTag["RD"] = 19] = "RD";
    SpriteTag[SpriteTag["LRD"] = 20] = "LRD";
    SpriteTag[SpriteTag["UD"] = 21] = "UD";
    SpriteTag[SpriteTag["LUD"] = 22] = "LUD";
    SpriteTag[SpriteTag["RUD"] = 23] = "RUD";
    SpriteTag[SpriteTag["LRUD"] = 24] = "LRUD";
    SpriteTag[SpriteTag["none"] = 25] = "none";
    SpriteTag[SpriteTag["white"] = 26] = "white";
    SpriteTag[SpriteTag["element_back"] = 27] = "element_back";
    SpriteTag[SpriteTag["element_gas_front"] = 28] = "element_gas_front";
    SpriteTag[SpriteTag["element_liquid_front"] = 29] = "element_liquid_front";
    SpriteTag[SpriteTag["element_vacuum_front"] = 30] = "element_vacuum_front";
    SpriteTag[SpriteTag["info_back"] = 31] = "info_back";
    SpriteTag[SpriteTag["info_front"] = 32] = "info_front";
})(SpriteTag = exports.SpriteTag || (exports.SpriteTag = {}));
