"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ZIndex = void 0;
var ZIndex;
(function (ZIndex) {
    ZIndex[ZIndex["NoLayer"] = -2] = "NoLayer";
    ZIndex[ZIndex["Background"] = -1] = "Background";
    ZIndex[ZIndex["Backwall"] = 1] = "Backwall";
    ZIndex[ZIndex["Gas"] = 2] = "Gas";
    ZIndex[ZIndex["GasConduits"] = 3] = "GasConduits";
    ZIndex[ZIndex["GasConduitBridges"] = 4] = "GasConduitBridges";
    ZIndex[ZIndex["LiquidConduits"] = 5] = "LiquidConduits";
    ZIndex[ZIndex["LiquidConduitBridges"] = 6] = "LiquidConduitBridges";
    ZIndex[ZIndex["SolidConduits"] = 7] = "SolidConduits";
    ZIndex[ZIndex["SolidConduitContents"] = 8] = "SolidConduitContents";
    ZIndex[ZIndex["SolidConduitBridges"] = 9] = "SolidConduitBridges";
    ZIndex[ZIndex["Wires"] = 10] = "Wires";
    ZIndex[ZIndex["WireBridges"] = 11] = "WireBridges";
    ZIndex[ZIndex["WireBridgesFront"] = 12] = "WireBridgesFront";
    ZIndex[ZIndex["LogicWires"] = 13] = "LogicWires";
    ZIndex[ZIndex["LogicGates"] = 14] = "LogicGates";
    ZIndex[ZIndex["LogicGatesFront"] = 15] = "LogicGatesFront";
    ZIndex[ZIndex["InteriorWall"] = 16] = "InteriorWall";
    ZIndex[ZIndex["GasFront"] = 17] = "GasFront";
    ZIndex[ZIndex["BuildingBack"] = 18] = "BuildingBack";
    ZIndex[ZIndex["Building"] = 19] = "Building";
    ZIndex[ZIndex["BuildingUse"] = 20] = "BuildingUse";
    ZIndex[ZIndex["BuildingFront"] = 21] = "BuildingFront";
    ZIndex[ZIndex["TransferArm"] = 22] = "TransferArm";
    ZIndex[ZIndex["Ore"] = 23] = "Ore";
    ZIndex[ZIndex["Creatures"] = 24] = "Creatures";
    ZIndex[ZIndex["Move"] = 25] = "Move";
    ZIndex[ZIndex["Front"] = 26] = "Front";
    ZIndex[ZIndex["GlassTile"] = 27] = "GlassTile";
    ZIndex[ZIndex["Liquid"] = 28] = "Liquid";
    ZIndex[ZIndex["Ground"] = 29] = "Ground";
    ZIndex[ZIndex["TileMain"] = 30] = "TileMain";
    ZIndex[ZIndex["TileFront"] = 31] = "TileFront";
    ZIndex[ZIndex["FXFront"] = 32] = "FXFront";
    ZIndex[ZIndex["FXFront2"] = 33] = "FXFront2";
    ZIndex[ZIndex["SceneMAX"] = 34] = "SceneMAX";
})(ZIndex = exports.ZIndex || (exports.ZIndex = {}));
