name: Build and Deploy

on:
  push:
    branches:
      - "master"

jobs:
  # Optional quick test check (non-blocking)
  quick-check:
    runs-on: ubuntu-latest
    continue-on-error: true  # Don't block deployment
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared library
        run: npm run build:lib

      - name: Compile TypeScript
        run: npm run tsc

  # Main deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: quick-check
    if: always()  # Always deploy regardless of quick-check result
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: docker build -t ${{ vars.IMAGE_NAME }} -f deploy.Dockerfile .
        
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
        
      - name: Tag image
        run: docker tag bni-deploy ${{ vars.DIGITALOCEAN_REGISTRY }}/${{ vars.IMAGE_NAME }}
        
      - name: Push image to DO Container Registry
        run: docker push ${{ vars.DIGITALOCEAN_REGISTRY }}/${{ vars.IMAGE_NAME }}
        
      - name: Report status
        run: |
          if [[ "${{ needs.quick-check.result }}" == "failure" ]]; then
            echo "⚠️ WARNING: Quick checks failed but deployment proceeded"
            echo "Please review any issues and run full test suite"
          else
            echo "✅ Deployment completed successfully"
          fi
